name: Build Cleepp

on:
  push:
    branches: [forkmain]
    paths-ignore:
      - ".github/**"
      - ".git/**"
      - ".gitignore"
      - "Designs/**"
      - "*Tests/**"
      - "*.md"
      - "*.toml"
      - "*.xml"
  workflow_dispatch:
    branches: [forkmain]

env:
  projectfile: Maccy.xcodeproj
  buildscheme: Cleepp

jobs:
  build:
    name: Build Cleepp Non-AppStore Variant
    runs-on: macos-14 # required to use Xcode 15, "macos-latest" is actually older and uses Xcode 14
    if: ${{ ! contains(github.ref, 'refs/tags') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Patch Xcode 15.3
        uses: 2sem/patch-package-resolved@v1
        # this fixes a mysterious build failure
        #   xcodebuild: error: Could not resolve package dependencies:
        #     Package.resolved file is corrupted or malformed; fix or delete the file
        #     to continue: unknown 'PinsStorage' version '3'
        # should probably remove this when upgrading the "runs-on" platform
      - name: Build
        run: |
          :
          xcodebuild -version
          
          # requires that env.projectfile is the name of the .xcodeproj, and env.buildscheme
          # is a valid build scheme,
          set -o pipefail && xcodebuild clean build analyze \
            -scheme "${{ env.buildscheme }}" -configuration Release \
            -project "${{ env.projectfile }}" -derivedDataPath . | \
            xcbeautify --renderer github-actions --preserve-unbeautified
